# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               von Wettberg Lab
tagline:             'Plant and Soil Science Lab'
description:         'We are a group of evolutionary ecologists who use tools from population genetics, agronomy, conservation biology and field ecology to study how population bottlenecks affect genetic diversity and stress tolerance in wild relatives of crops and in endangered species.  Most of our work is on the wild relatives of chickpea, but we also work with lentil, fenugreek, mungbeans, and mangoes.'
url:                 http://lanyon.getpoole.com
baseurl:             '/projects/'
paginate:            5

# About/contact
author:
  name:              Eric Bishop von Wettberg
  url:               http://ericvonwettberg.wixsite.com/laboratory
  email:             Eric.Bishop-Von-Wettberg@uvm.edu

# Custom vars
version:             1.0.0
